services:
  - type: web
    name: naturaltrekking
    env: node
    plan: free
    buildCommand: |
      cd naturaltrekking && npm install && npm run build
      cd .. && npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:16945436%40Aa1234@db.tqyvpdjbqxwenmuuzhul.supabase.co:5432/postgres
      - key: JWT_SECRET
        value: claveAdmin1234
      - key: ORS_API_KEY
        value: 5b3ce3597851110001cf624809bbb23ff97f47babf665274bf269e35
      - key: REACT_APP_API_URL
        value: https://naturaltrekking.onrender.com
      - key: PORT
        value: 10000
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html

databases:
  - name: naturaltrekkingdb
    engine: postgresql
    version: 16
    plan: free
    ipAllowList: []