services:
  - type: web
    name: naturaltrekking
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:16945436%40Aa1234@db.tqyvpdjbqxwenmuuzhul.supabase.co:5432/postgres
      - key: JWT_SECRET
        value: claveAdmin1234
      - key: ORS_API_KEY
        value: 5b3ce3597851110001cf624809bbb23ff97f47babf665274bf269e35
      - key: REACT_APP_API_URL
        value: https://naturaltrekking.onrender.com
    routes:
      - type: rewrite
        source: /!(api|static|assets)/*
        destination: /index.html

databases:
  - name: naturaltrekkingdb
    engine: postgresql
    version: 16
    plan: free
    ipAllowList: []